functionsDirectory = "C:\\Users\\undre\\.gemini\\antigravity\\scratch\\srj website\\skid_row_joe_national_resource_bank_by_therealdocjordan\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "C:\\Users\\undre\\.gemini\\antigravity\\scratch\\srj website\\skid_row_joe_national_resource_bank_by_therealdocjordan"
publishOrigin = "config"
functions = "C:\\Users\\undre\\.gemini\\antigravity\\scratch\\srj website\\skid_row_joe_national_resource_bank_by_therealdocjordan\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"